= Tibero
:toc:
:toclevels: 2
:icons: font
:imagesdir: ./src/img
:doctype: book
:docdate: 2023-04-03
:sectlinks:
:source-highlighter: highlight.js

REFR::

* https://sy-dev.tistory.com/30[Spring Boot + My Batis + Tibero6 + gradle]
* https://keepbang.tistory.com/5[Spring Boot + tibero + mybatis 연동하기]

== Environment

- Windows 10 Home 64bit
- JRE 1.8


=== version
- tibero 6
- license `2023.04.03` ~ `2023.10.03`

=== tools

- Tibero Admin

=== config
[%autowidth]
|==== 
| Name | Localhost 
| Server IP | localhost 
| Port | 8629 #(default)#
| User | sys #(default)#
| DB Nmae (SID) | tibero #(default)#
| Character Set | UTF8
| DB Type | TIBERO_6X
|==== 

== Getting Started


=== Spring Boot

[upperroman]
. build.gradle에 dependencies 추가

+

====
implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.1'
====

+

CAUTION: java 17 이라서 3.x버전 + 
java 8 이라면 2.x 버전

. application.properties 추가

+

====
_# tibero setting_ +
spring.datasource.url=jdbc:tibero:thin:@[host]:[port]:[DB Name] +
spring.datasource.username=[account] +
spring.datasource.password=[password] +
spring.datasource.driver-class-name=com.tmax.tibero.jdbc.TbDriver +

_# mybatis setting_ +
mybatis.config-location=classpath:mybatis-config.xml +
mybatis.mapper-locations=mappers/****/*.xml +
====

. SqlSession @Bean 추가

+

[source,java]
----
package [package];

import javax.sql.DataSource;

import org.apache.ibatis.session.SqlSessionFactory;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

@SpringBootApplication
@MapperScan(value= {"[package].mapper"})
public class [project name]Application {
	public static void main(String[] args) {
		SpringApplication.run([project name]Application.class, args);
	}
	
    //SqlSessionFactory 설정 
	@Bean
	public SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
		final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
		
		sessionFactory.setDataSource(dataSource);
		
		Resource configLocation = new PathMatchingResourcePatternResolver().getResource("classpath:mybatis-config.xml");
		
		sessionFactory.setConfigLocation(configLocation);
		
		return sessionFactory.getObject();
	}
}
----

. src/main/resources에 mybatis-confi.xml 추가

+

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
"http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
    <typeAliases>
    
    </typeAliases>
    <mappers>
        <mapper resource="mappers/[mapper name].xml"/>
    </mappers>
</configuration>
----